#!/bin/bash

# Create necessary directories if needed
# Needed for 'fbg()'
if [[ ! -d ~/Pictures/wallpapers ]]; then
    highlight "Creating ~/Pictures/wallpapers"
    mkdir -p  ~/Pictures/wallpapers
fi
# Needed for make-screenshot
if [[ ! -d ~/Pictures/screenshots ]]; then
    highlight "Creating ~/Pictures/screenshots"
    mkdir -p  ~/Pictures/screenshots
fi

# Add udev rules to allow the use of xbacklight without sudo
read -r -p "Add udev.rules to allow non-sudo xbacklight? [y|N] " response
if [[ $response =~ (y|yes|Y) ]]; then
    echo 'ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", GROUP="video", MODE="0664"' \
        | sudo tee /etc/udev/rules.d/backlight.rules > /dev/null
fi

# Set default ALSA device in /etc/asound.conf
read -r -p "Set default ALSA device? [y|N] " response
if [[ $response =~ (y|yes|Y) ]]; then
    read -r -p "Enter the device number: " device_num
    echo "defaults.pcm.card ${device_num}
defaults.ctl.card ${device_num}" \
    | sudo tee /etc/asound.conf > /dev/null
fi

read -r -p "Setup oh-my-zsh? [y|N]" response
if [[ $response =~ (y|yes|Y) ]]; then
    highlight "Installing Oh-My-Zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/loket/oh-my-zsh/feature/batch-mode/tools/install.sh)" -s --batch || {
        echo "Could not install Oh My Zsh" >/dev/stderr
        exit 1
    }
    highlight "Cloning zsh-syntax-highlighting"
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.config/zsh/custom}/plugins/zsh-syntax-highlighting
    highlight "Cloning zsh-completions"
    git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.config/zsh/custom}/plugins/zsh-completions
    highlight "Cloning zsh-autosuggestions"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.config/zsh/custom}/plugins/zsh-autosuggestions
    highlight "Copying theme"
    cp ./zsh/themes/lambda.zsh-theme ~/.config/zsh/custom/themes/
    highlight "Copying Settings"
    cp ./zsh/*.zsh ~/.config/zsh/
    highlight "Copying .zshrc"
    mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
fi
