#!/bin/bash
id=37913582
timer=15m
resolution=1920x1080

while true
do
	wget https://source.unsplash.com/collection/${id}/${resolution} -O ~/.cache/wall
	feh --no-fehbg --bg-scale ~/.cache/wall
	sleep ${timer}
done

