#!/bin/bash

dir_name=~/Pictures/wallpapers
wait_time=15m

while true
do
    readarray -t -d '' pathnames < <( find $dir_name -type f -print0 | shuf -z )
    for pathname in "${pathnames[@]}"; do
        feh --bg-fill --no-fehbg $pathname
        sleep $wait_time
    done
done
